services:
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "15432:5432"

    environment:
      - POSTGRES_PASSWORD=stat-db
      - POSTGRES_USER=stat-db
      - POSTGRES_DB=stat-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_DB=ewm-db
      - POSTGRES_USER=ewm-db
      - POSTGRES_PASSWORD=ewm-db
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10



