CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT category_name_len CHECK (LENGTH(category_name) >= 1 AND LENGTH(category_name) <= 50)
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    initiator_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    state VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    event_date TIMESTAMP WITHOUT TIME ZONE,
    published_at TIMESTAMP WITHOUT TIME ZONE,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INTEGER NOT NULL DEFAULT 0,
    request_moderation BOOLEAN NOT NULL DEFAULT FALSE,
    location_id BIGINT NOT NULL,
    CONSTRAINT annotation_len CHECK (LENGTH(annotation) >= 20 AND LENGTH(annotation) <= 2000),
    CONSTRAINT description_len CHECK (LENGTH(description) >= 20 AND LENGTH(description) <= 7000),
    CONSTRAINT title_len CHECK (LENGTH(title) >= 3 AND LENGTH(title) <= 120)
    );

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN DEFAULT FALSE NOT NULL,
    title VARCHAR(50) UNIQUE NOT NULL,
    CONSTRAINT title_len CHECK (LENGTH(title) >= 1 AND LENGTH(title) <= 50)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT,
    event_id BIGINT,
    PRIMARY KEY (compilation_id, event_id)
);


ALTER TABLE events
DROP CONSTRAINT IF EXISTS fk_events_category_id;
ALTER TABLE events
    ADD CONSTRAINT fk_events_category_id FOREIGN KEY (category_id)
        REFERENCES categories (id) ON DELETE CASCADE;

ALTER TABLE events
DROP CONSTRAINT IF EXISTS fk_events_location_id;
ALTER TABLE events
    ADD CONSTRAINT fk_events_location_id FOREIGN KEY (location_id)
        REFERENCES locations (id) ON DELETE CASCADE;

ALTER TABLE compilations_events
DROP CONSTRAINT IF EXISTS fk_compilations_events_compilation_id;
ALTER TABLE compilations_events
    ADD CONSTRAINT fk_compilations_events_compilation_id FOREIGN KEY (compilation_id)
        REFERENCES compilations (id) ON DELETE CASCADE;

ALTER TABLE compilations_events
DROP CONSTRAINT IF EXISTS fk_compilations_events_event_id;
ALTER TABLE compilations_events
    ADD CONSTRAINT fk_compilations_events_event_id FOREIGN KEY (event_id)
        REFERENCES events (id) ON DELETE CASCADE;